name: Build Test - SWA-apps:Test-ACR

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        app:
#           - StaticWebAppsSamples/HugoClientDotNetCoreServer
#           - StaticWebAppsSamples/ReactClientNodeServer/app
            - StaticWebAppsSamples/nextjs-starter-main
#           - StaticWebAppsSamples/angular-basic-main
#           - StaticWebAppsSamples/blazor-basic-main/Client
#           - StaticWebAppsSamples/blazor-sample/Client
#           - StaticWebAppsSamples/blazor-starter-main/Client
#           - StaticWebAppsSamples/mongoose-starter-main
#           - StaticWebAppsSamples/nextjs-csr-ssg-isr
#           - StaticWebAppsSamples/nextjs-starter-main
#           - StaticWebAppsSamples/next-with-static-export
#           - StaticWebAppsSamples/nuxt-3-starter-main
#           - StaticWebAppsSamples/nuxtjs-starter-main
#           - StaticWebAppsSamples/react-basic-main
#           - StaticWebAppsSamples/roles-function-main
#           - StaticWebAppsSamples/StartupAdventurer-main
#           - StaticWebAppsSamples/svelte-basic-main
#           - StaticWebAppsSamples/vanilla-api-main
#           - StaticWebAppsSamples/vanilla-basic-main
#           - StaticWebAppsSamples/vue-basic-main
#           - StaticWebAppsSamples/hugo-example.github.io-master
#           - StaticWebAppsSamples/hugoBasicsExample-master
#           - StaticWebAppsSamples/sample-hugo-main
#           - StaticWebAppsSamples/vue-basic-main  
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/oryx
          ref: snehapar/Test-SWA-for-all-platforms
      - name: Oryx build step
        uses: snehapar9/jamstacktest-composite-action-private-image@snehapar/oryx-build
        id: oryx-build
        with:
          app-location: ./tests/SampleApps/${{ matrix.app }} 
    
