name: SWA Test - nodejs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:      
        app:
          - nodejs/angular14app
          - nodejs/create-react-app-sample
          - nodejs/helloworld-nuxtjs
          - nodejs/monorepo-lerna-npm
          - nodejs/nextjs-yarn2-example
          - nodejs/NodeAndTypeScriptHelloWorld
          - nodejs/node-mssql
          - nodejs/node-postgres
          - nodejs/vuepress
          - nodejs/webfrontend-yarnlock
          - nodejs/websocket
        versionString: 
          - "--platform nodejs --platform-version 12"
          - "--platform nodejs --platform-version 14"
          - "--platform nodejs --platform-version 16"
          - "--platform nodejs --platform-version 18"
        exclude:
          - app: nodejs/angular14app
            versionString: "--platform nodejs --platform-version 12"
          - app: nodejs/angular14app
            versionString: "--platform nodejs --platform-version 16"
          - app: nodejs/NodeAndTypeScriptHelloWorld
            versionString: "--platform nodejs --platform-version 16"


    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm --no-cache -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:github-actions-bullseye oryx build /app ${{ matrix.versionString }} --debug
